name: final_login
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  web_socket_channel: ^2.1.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^9.5.2
  google_fonts: ^6.2.1
  quickalert: ^1.1.0
  table_calendar: ^3.0.9
  flutter_localization: ^0.2.1
  sleek_circular_slider: ^2.0.1
  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4
  get_it: ^7.6.7
  auto_route_generator: ^7.3.2
  shared_preferences: ^2.2.2
  salomon_bottom_bar: ^3.3.2
  animated_notch_bottom_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  toggle_switch: ^2.3.0
  flutter_barcode_scanner: ^2.0.0
  line_awesome_flutter: ^2.0.0
  get: ^4.6.6
  url_strategy: ^0.2.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.jpeg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
  # Adding flutter_localizations as part of the Flutter SDK
  generate: true
